# Site settings
title: Kerry's Blog
email: rosenberg.kerry@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  klrosenberg

# Build settings
markdown: redcarpet
